### ISSUE TITLE
Unable to use Factor on certain numbers

### ISSUE THREAD

**Issue by AlexDikelsky** [mlochbaum/bqn-libs#1]
I was trying to get an iterator of factorizations, and got an error for certain numbers. I was using CBQN, and ran
```
p ← •Import "primes.bqn"

•Out •Repr p.Factor 7718429
•Out •Repr p.Factor 255
•Out •Repr p.Factor 256
•Out •Repr p.Factor 258
•Out •Repr p.Factor 259

•Out •Repr p.Factor 257
```
When I tried to run it, I got
```
2081‿3709
3‿5‿17
2‿2‿2‿2‿2‿2‿2‿2
2‿3‿43
7‿37
Error: ´: No identity found
/home/alexdikelsky/euler/prob_451/primes.bqn:106:
    Pow ← Mul{𝔽´𝔽˜⍟(/2|⌊∘÷⟜2⍟(↕·⌈2⋆⁼⊢)𝕩)𝕨}
               ^
/home/alexdikelsky/euler/prob_451/primes.bqn:115:
    C ← { 𝕊a: s MR a Pow d }  # Is composite
                   ^
13: source unknown
12: source unknown
/home/alexdikelsky/euler/prob_451/primes.bqn:116:
    0 {𝕨<⟜≠◶⟨1,C∘⊑◶⟨+⟜1⊸𝕊,0⟩⟩𝕩} Witnesses 𝕩
        ^^^^^^^^^^^^^^^^^^^^^
/home/alexdikelsky/euler/prob_451/primes.bqn:116:
    0 {𝕨<⟜≠◶⟨1,C∘⊑◶⟨+⟜1⊸𝕊,0⟩⟩𝕩} Witnesses 𝕩
    ^
9: source unknown
8: source unknown
/home/alexdikelsky/euler/prob_451/primes.bqn:91:
    c◶⟨(×˜¯1⊑p)⊸<◶1‿MillerRabin, 0⟩ 𝕩
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6: source unknown
5: source unknown
4: source unknown
/home/alexdikelsky/euler/prob_451/primes.bqn:159:
    2⊸⌊◶⟨!∘"Can't factor 0", 2‿0⊸⥊, IsPrime◶⟨FactorTrial, ≍˘≍⟜1⟩⟩ 𝕩
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2: source unknown
1: source unknown
factor.bqn:9:
  •Out •Repr p.Factor 257
               ^^^^^^

```

It looks like 257 doesn't work, but the numbers around it work fine. [257 is prime](https://www.wolframalpha.com/input/?i=factor+257). Factoring the next prime ([263](https://www.wolframalpha.com/input/?i=prime+after+257)) works fine.

**Comment by mlochbaum** [comment]
Thanks! It was a problem with Miller-Rabin testing, so it affects `IsPrime` too. Situation seems to be that the number being tested gets through trial division (by 2, 3, 5, and 7), but is in the right range that M-R ends up with an exponent of 1. Changing `𝔽´` to `1𝔽´` would have worked, but also slowed things down with an extra `Mul` call, so I did something slightly more complicated.

**Comment by mlochbaum** [comment]
Added a warning to the Fifty Functions [translation](https://github.com/mlochbaum/BQN/blob/master/examples/fifty.bqn) I took this from as well; [Roger's version](https://www.jsoftware.com/papers/50/50_34.htm) has the same issue.
