### ISSUE TITLE
Small primes not called prime by IsPrime

### ISSUE THREAD

**Issue by AlexDikelsky** [mlochbaum/bqn-libs#2]
When I run
```
primes ← •Import "primes.bqn"
•Out¨ •Repr¨ (primes.IsPrime 2+(↕30)) ∾¨ 2+(↕30)
```
in CBQN, I get that 2, 3, 5, 7 are not primes. I'm using the most recent version of `bqn-libs`.

**Comment by mlochbaum** [comment]
Little catch with trial division: a number that divides itself might just not be composite. Thanks again for the testing service.
