### ISSUE TITLE
CSV Parsing setup

### ISSUE THREAD

**Issue by tankorsmash** [mlochbaum/bqn-libs#7]
Hi there, for work I'm trying out BQN for data analysis, instead of Python, and it took me nonzero time to figure this out, so I'm leaving this here in case it helps anyone else.

Below is how I had to do it, where you are supposed to pass in a character for double quotes, comma, and a literal newline. In vim, you can insert a newline with `<Ctrl-Q>`+`<Enter>`. 

```bqn
csv ← ['"',',','^M'] •Import "../bqn-libs/csv.bqn"
data ← csv.SplitL •file.Lines "../my_data.csv"
```

The tests use instead `"',/"`, because I guess they're easier to type, but having the 'proper' ones listed somewhere explicitly would be nice.

Thanks for the library, and BQN!

**Comment by mlochbaum** [comment]
This should be the same as the defaults that are set if you don't pass in any `•args` (implicitly `⟨⟩`), written `""","∾@+10` on line 9. I'll add some sort of comment, but does using `•Import "../bqn-libs/csv.bqn"` with no left argument work for you?

I'd write your left argument as `⟨'"',',',@+10⟩`, by the way. `[]` works but it's intended to be used when the values are arrays, not atoms.

**Comment by tankorsmash** [comment]
Perfect, without arguments it worked as well!

I used the tests as instructions, so I assumed that's how it needed to be done.

> I'd write your left argument as `⟨'"',',',@+10⟩`, by the way. `[]` works but it's intended to be used when the values are arrays, not atoms.

Excellent, I'll do that too. I had tried `["'," (@+10)]`, at least I was close.

Thanks again!

**Comment by mlochbaum** [comment]
Oh, not really the same as the Vim shortcut writes a carriage return `@+13`, not a newline `@+10`. But the reason either one works is that `SplitL` takes lines so all the line breaks have been parsed out, whatever they are (newlines probably).
